apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: zero-trust-workload-identity-manager
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    name: zero-trust-workload-identity-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      name: zero-trust-workload-identity-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: zero-trust-workload-identity-manager
      labels:
        name: zero-trust-workload-identity-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /usr/bin/zero-trust-workload-identity-manager
        args:
          - --health-probe-bind-address=:8081
          - --v=$(OPERATOR_LOG_LEVEL)
          - --metrics-bind-address=$(METRICS_BIND_ADDRESS)
          - --metrics-secure=$(METRICS_SECURE)
        ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: zero-trust-workload-identity-manager
        - name: OPERATOR_VERSION
          value: 1.0.1
        - name: RELATED_IMAGE_SPIRE_SERVER
          value: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-spire-server-rhel9@sha256:6a14fb03c3b7256a405cff52ae0e5c7e66b1fa1a8e3a955d6670123f5534d4e4
        - name: RELATED_IMAGE_SPIRE_AGENT
          value: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-spire-agent-rhel9@sha256:54865d9de74a500528dcef5c24dfe15c0baee8df662e76459e83bf9921dfce4e
        - name: RELATED_IMAGE_SPIFFE_CSI_DRIVER
          value: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-csi-driver-rhel9@sha256:5359e8709d1b73386eddef202d59b7c511aa5366ca04f5ee707bbf760977e55d
        - name: RELATED_IMAGE_SPIRE_OIDC_DISCOVERY_PROVIDER
          value: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-spire-oidc-discovery-provider-rhel9@sha256:70f04312f96851a37ec9bfcc605d6a7edb4c87b548621007183b7caa2333816a
        - name: RELATED_IMAGE_SPIRE_CONTROLLER_MANAGER
          value: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-spire-controller-manager-rhel9@sha256:7ddf330a798dbb112c2f58d2548941100a964db705617680d09969eaa3e07727
        - name: RELATED_IMAGE_NODE_DRIVER_REGISTRAR
          value: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9@sha256:1c480fa5089a32cf804fc84df7219ca64066cbac2eeb962c4385754132c3873b
        - name: RELATED_IMAGE_SPIFFE_CSI_INIT_CONTAINER
          value: registry.access.redhat.com/ubi9@sha256:dec374e05cc13ebbc0975c9f521f3db6942d27f8ccdf06b180160490eef8bdbc
        - name: OPERATOR_LOG_LEVEL
          value: "2"
        - name: METRICS_BIND_ADDRESS
          value: ":8443"
        - name: METRICS_SECURE
          value: "true"
        image: controller:latest
        name: manager
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
